Get localhost name dynamically
Some OEMs need to use a hostname different from "localhost". The CTS
tests assume that the hostname is always localhost; which makes some SSL
tests fail if the name has been changed (since the certificate does not
match)

Getting the actual hostname of the device dynamically before the tests
allows them to pass.

The module with the failing tests is CtsLibcoreTestCases, and the tests
are failing with the exception:
javax.net.ssl.SSLPeerUnverifiedException: Hostname android-idc not verified: certificate: sha1/k4mkoVM77WbF7WNLQSshUBjxxDA= DN: CN=Local Host subjectAltNames: [localhost]

Bug: 325912458
Test: Manual run of the corresponding CTS module
Change-Id: Ic83dd87c00a1407589f3797548153be2e3bb3ef3